# Site
title: Ramzan Bekbulatov
bio: Software Engineer
description: Personal site
locale: en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rmbk.me" # the base hostname & protocol for your site
repository: uburuntu/uburuntu.github.io

# Social
linkedin: rmbk
twitter: real_rmbk
vk: rm_bk
telegram: rm_bk
instagram: rm_bk
github: uburuntu
email: bekbulatov.ramzan@ya.ru

# SEO & Social Sharing (jekyll-seo-tag)
author:
  name: Ramzan Bekbulatov
  twitter: real_rmbk
twitter:
  username: real_rmbk
  card: summary_large_image
social:
  name: Ramzan Bekbulatov
  links:
    - https://github.com/uburuntu
    - https://linkedin.com/in/rmbk
    - https://twitter.com/real_rmbk

# Default image for social sharing (og:image)
image: /images/me.jpg

# Other
background_image: /images/bg.jpg
# Tip: The color palette and other styles can be configured in /_sass/lib/_vars.scss

defaults:
  - scope:
      path: ""
      type: posts
    values:
      permalink: "/blog/:title/"
      layout: post
      author:

# Jekyll
permalink: /blog/:title/
markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
mathjax: true
sass:
  sass_dir: _sass
  style: compressed
  quiet_deps: true

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

# Exclude list
exclude:
  [
    README.md,
    Gemfile,
    Gemfile.lock,
    node_modules,
    gulpfile.js,
    package.json,
    _site,
    src,
    vendor,
    CNAME,
    LICENSE,
    Rakefile,
    old,
    docker-compose.yml,
  ]
